version: 2

jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run linter
          command: npm run lint

  audit:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - run:
          name: update-npm
          command: "npm install -g npm"

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: run-audit-ci
          command: npx audit-ci@^6 --config ./audit-ci.jsonc
  
      - run:
          name: install-npm
          command: "npm install --no-audit"
      

workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - main
                - master
      - audit:
          requires:
            - lint
