apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name  }}-ingress
  annotations:
    {{- if eq .Values.werf.env "stage" }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- end }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains always";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
{{- $environment := index .Values .Values.werf.env }}
spec:
  tls:
  - hosts:
    - {{ $environment.config.host }}
    - {{ print "www." $environment.config.host }}
    secretName: {{ $environment.secretName }}
  rules:
  - host: {{ $environment.config.host }}
    http:
      paths:
      - path: /tst
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name  }}-service
            port: 
              number: {{ $environment.port }}